version: '3.8'

services:
  f5tts_api:
    build: .
    command: python -m uvicorn f5_tts.api_server:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
